config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations",
    passwords: "users/passwords"}
  root to: 'goals#index'
  resources :goals, shallow: true do
    resources :action_records
    resources :goal_actions
    get 'user', on: :collection
    get 'tumiage', on: :collection
  end
  resources :users
  get 'statics/help'
  get 'statics/policy'
  get 'statics/how'
  resources :rooms
  
  mount ActionCable.server => '/cable'
end

app/controllers/goal_actions_controller.rb
class GoalActionsController < ApplicationController
    before_action :authenticate_user!, only:[:new, :edit, :destroy]
    before_action :correct_user, only: [:edit, :update]

    def index
        @goal = Goal.find(params[:goal_id])
        @goal_actions = @goal.goal_actions
    end

    def new
        @goal_action = GoalAction.new
        @goal = Goal.find(params[:goal_id])
        @user = @goal.user
        redirect_to(root_path) unless current_user?(@user)
    end

    def create
        @goal_action = GoalAction.new(goal_action_params)
        @goal = Goal.find(params[:goal_id])
        @goal_action.user_id = current_user.id
        @goal_action.goal_id = params[:goal_id]

        if @goal_action.save
            redirect_to action: :index
            flash[:success] = "保存しました"
        else
            render :new
        end
    end

    def edit
        @goal_action = GoalAction.find(params[:id])
        @goal = @goal_action.goal
    end

    def update
        @goal_action = GoalAction.find(params[:id])
        @goal = @goal_action.goal
        @goal_action.assign_attributes goal_action_params
        if @goal_action.save
            redirect_to goal_goal_actions_path(@goal)
            flash[:success] = "保存しました"
        else
            redirect_back(fallback_location: root_path)
            flash[:warning] = "保存できませんでした"
        end
    end

    def destroy
        @goal_action = GoalAction.find(params[:id])
        @goal = @goal_action.goal
        if @goal_action.user_id == current_user.id
            @goal_action.destroy
            redirect_to goal_goal_actions_path(@goal)
            flash[:warning] = "行動を削除しました"
        end
    end

    private
    def goal_action_params
        params.require(:goal_action).permit(
            :action_name, :goal_id)
    end

    def correct_user
        @user = GoalAction.find(params[:id]).user
        redirect_to(root_path) unless current_user?(@user)
    end
end

app/views/goal_actions/_form.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h4 行動追加
            - if @goal_action.errors.present?
                ul#error_explanation
                    - @goal_action.errors.full_messages.each do |message|
                        li = message
            = form_for [@goal, @goal_action] do |f|
                .form-group
                    = f.label :行動名
                    = f.text_field :action_name, class: 'form-control', placeholder: "お菓子の代わりにフルーツを食べる"
                = f.submit "登録", class:"btn btn-primary btn-block"
                .text-left
                    = link_to "戻る", :back,class: 'btn btn-light btn-block my-3'
        .col-md-1

app/views/goal_actions/edit.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h4 行動追加
            - if @goal_action.errors.present?
                ul#error_explanation
                    - @goal_action.errors.full_messages.each do |message|
                        li = message
            = form_with model: @goal_action, local: true do |f|
                .form-group
                    = f.label :行動名
                    = f.text_field :action_name, class: 'form-control'
                = f.submit "登録", class:"btn btn-primary btn-block"
                .text-left
                    = link_to "戻る", :back,class: 'btn btn-light btn-block my-3'
        .col-md-1

app/views/goal_actions/index.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h4 #{@goal.goal_content}の行動一覧
            table.table.table-borderless.table-striped
                thead
                    tr
                        th 
                        th
                    tbody
                            - @goal_actions.each.with_index(1) do |goal_action, index|
                                tr
                                    th scope="row" 行動#{index}
                                    td 
                                        = goal_action.action_name
                                        - if @goal.user_id == current_user&.id
                                            .text-right
                                                = link_to '編集', edit_goal_action_path(goal_action), class: 'btn btn-primary mr-3'
                                                = link_to '削除', goal_action_path(goal_action), method: :delete, remote: true, class: 'btn btn-primary mr-3'
            = link_to '目標詳細に戻る', goal_path(@goal), class: 'btn btn-light m-3'
            - if @goal.user_id == current_user&.id
                = link_to '行動を追加', new_goal_goal_action_path, class: 'btn btn-light m-3'
        .col-md-1