config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations",
    passwords: "users/passwords"}
  root to: 'goals#index'
  resources :goals, shallow: true do
    resources :action_records
    resources :goal_actions
    get 'user', on: :collection
    get 'tumiage', on: :collection
  end
  resources :users
  get 'statics/help'
  get 'statics/policy'
  get 'statics/how'
  resources :rooms
  
  mount ActionCable.server => '/cable'
end

app/models/goal.rb
class Goal < ApplicationRecord
    validates :goal_content, presence: true
    validates :identity_content, presence: true
    validates :rank, presence: true

    belongs_to :user
    belongs_to :goal_category

    has_many :goal_actions, dependent: :destroy
    has_many :action_records, dependent: :destroy

    accepts_nested_attributes_for :goal_actions
end

app/models/goal_action.rb
class GoalAction < ApplicationRecord
    validates :action_name, presence: true

    belongs_to :user, optional: true
    belongs_to :goal, optional: true

    has_many :action_records, dependent: :destroy
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :authenticate_user!, only:[:new, :edit, :destroy, :user]
    before_action :correct_user, only: [:edit, :update]
    
    def index
        @goal_categories = GoalCategory.all
        if params[:search].present?
            @goals = Goal.where('goal_content LIKE ?', "%#{params[:search]}%").order(rank: "DESC").page(params[:goal_page])
        elsif params[:goal_category_id].present?
            @goal_category = GoalCategory.find(params[:goal_category_id])
            @goals = @goal_category.goals.order(rank: "DESC").page(params[:goal_page])
        else
            #rank順に並べる
            @goals = Goal.order(rank: "DESC").page(params[:goal_page])
        end
        @action_records = ActionRecord.all.order(id: "DESC").page(params[:action_record_page])
    end

    def new
        @goal = Goal.new
        @goal.goal_actions.build
    end

    def create
        @goal = current_user.goals.create(goal_params)
        if @goal.save
            redirect_to user_goals_path(id: current_user.id)
            flash[:success] = "保存しました"
        else
            render :new
        end
    end

    def edit
        @goal = Goal.find(params[:id])
        @goal_categories = GoalCategory.all
    end

    def show
        @goal = Goal.find(params[:id])
        @goal_actions = @goal.goal_actions
        @action_record = ActionRecord.new
    end

    def update
        @goal = Goal.find(params[:id])
        @goal.assign_attributes goal_params
        if @goal.save && @goal.user_id == current_user.id
            redirect_to user_goals_path(id: current_user.id)
            flash[:success] = "保存しました"
        else
            render :edit
        end
    end

    def destroy
        @goal = Goal.find(params[:id])
        if @goal.user_id == current_user.id
            @goal.destroy
            redirect_to goals_url
            flash[:warning] = "目標を削除しました"
        end
    end

    def user
        #目標が最新のもの順に並べる
        @goals = Goal.where(user_id: current_user.id).order(id: "DESC")
    end

    def tumiage
        # TODO バグなければ消す
        @action_records = ActionRecord.all.order(id: "DESC")
    end

    private
    def goal_params
        params.require(:goal).permit(
            :goal_content,:identity_content,:rank,:goal_category_id,
            goal_actions_attributes: [:id, :action_name, :user_id]
        )
    end

    def correct_user
        @user = Goal.find(params[:id]).user
        redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.slim
- if @goal.errors.present?
    ul#error_explanation
        - @goal.errors.full_messages.each do |message|
            li = message

= form_with model: @goal, local: true do |f|
    .form-group
        = f.label :goal_content
        = f.text_field :goal_content, class: 'form-control', placeholder: "2月までに3kg痩せる"
        small.form-text.text-muted 抽象的な目標ではなく、数値などを入れた具体的な目標にすることで、達成率を上げることができます。
    .form-group
        = f.fields_for :goal_actions do |af|
            = af.hidden_field :user_id, value: current_user.id
            = af.label :行動
            small.text-muted  ※後で違う行動も追加できます!
            = af.text_field :action_name, class: 'form-control', placeholder: "朝起きたら、HIITを4分やる"
            small.form-text.text-muted 
                | 毎日できるような、ハードルが低い行動にすると、続けやすいためおすすめです。
                br
                | やる時間なども決めると、行動ができる確率をあげることができます。
    .form-group
        = f.label :identity_content
        = f.text_field :identity_content, class: 'form-control', placeholder: "健康的でいたい"
        small.form-text.text-muted 
            | その目標を達成したいと思った自分の価値観を書いてください。
            br
            | これを書くことで、その目標が人から言われたことではなく、自分の意志で本当に達成したいと思った目標なのか確認できます。
    .form-group
        = f.label :カテゴリー
        = f.collection_select(:goal_category_id, GoalCategory.all, :id, :name, {prompt: false}, {class: "form-control"})
    .text-center
        = f.submit "登録", class:"btn btn-primary btn-block"
        = link_to "戻る", :back,class: 'btn btn-light btn-block my-3'

app/views/goals/_goal.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            - if current_user.present? && current_user.goals.blank?
                .card.bg-light.mb-3
                    .card-body 
                        .card-title 
                            h5 目標を登録してみよう!
                        .card-text
                            = link_to '登録する', new_goal_path, class:'btn btn-primary mt-3'
            - if current_user.blank?
                .card.bg-light.mb-3
                    .card-body 
                        .card-title 
                            h5 ログインして目標を登録してみよう!
                        .card-text
                            = link_to 'ログイン', new_user_session_path, class:'btn btn-primary mt-3'

app/views/goals/edit.slim
= render partial: 'form'

app/views/goals/index.slim
head
    script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9016715250972118" 
ul#myTab.nav.nav-tabs role="tablist" 
    li.nav-item
        a#goal-tab.nav-link.active aria-controls="goal" aria-selected="true" data-toggle="tab" href="#goal" role="tab"  みんなの目標
    li.nav-item
        a#action_record-tab.nav-link aria-controls="action_record" aria-selected="false" data-toggle="tab" href="#action_record" role="tab"  みんなの積み上げ
#myTabContent.tab-content
    #goal.tab-pane.fade.show.active aria-labelledby="goal-tab" role="tabpanel"
        .container
            .row
                .col-md-1
                .col-md-10.col-sm-12
                    br
                    ul.navbar-nav
                        li.nav-item.dropdown
                            a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
                                i.fa.fa-folder-open カテゴリ
                            .dropdown-menu aria-labelledby="navbarDropdown"
                                = link_to "すべて", goals_path, class: 'dropdown-item'
                                - @goal_categories.each do |gc|
                                    = link_to "#{gc.name}", goals_path(goal_category_id:gc.id), class: 'dropdown-item'
                        = form_tag(goals_path,:method => 'get', class:'form-inline') do 
                            = text_field_tag :search, nil, {class: 'form-control mr-sm-2', placeholder: "目標を入力"}
                            = submit_tag '検索', :name => nil, class: 'btn btn-outline-success my-2 my-sm-0'
                        .col-md-1
                .col-md-1
            .row
                .col-md-1
                .col-md-10.col-sm-12
                    / div align="center"
                    /     script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" 
                    /     /! 横長
                    /     ins.adsbygoogle data-ad-client="ca-pub-9016715250972118" data-ad-format="auto" data-ad-slot="1397969627" data-full-width-responsive="true" style="display:block" 
                    /     javascript:
                    /         (adsbygoogle = window.adsbygoogle || []).push({});
                .col-md-1
        = render partial: 'goal'
        .container
            .row
                .col-md-1
                .col-md-10.col-sm-12
                    - @goals.each do |goal|
                        .card.bg-light.my-3
                            .card-body
                                .row
                                    .col-4.col-md-2
                                        .card-text
                                            - if goal.user.icon.url.present?
                                                = image_tag goal.user.icon.url, class:'image', width: '60px'
                                            - else 
                                                = image_tag 'human.PNG', class:'image', width: '60px'
                                            br
                                            p = link_to "#{goal.user.display_name}", user_path(goal.user.id), class: 'my-1'
                                    .col-8.col-md-8
                                        h5.card-title
                                            br
                                            = goal.goal_content
                                p.card-text
                                    i.fa.fa-star
                                    = "達成Lv.#{goal.rank}"
                                    .progress 
                                        .progress-bar.progress-bar-striped aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" style="width: #{goal.rank * 10}%"
                                h6.card-text
                                    = link_to "#{goal.goal_category.name}", goals_path(goal_category_id:goal.goal_category.id),
                                        class: 'btn btn-outline-primary btn-sm mr-1'
                                    - if goal.user == current_user && goal.action_records.blank?
                                        .balloon1
                                            p 積み上げ記録をつけてみよう
                                hr
                                h6.card-text
                                    = link_to '詳細', goal_path(goal), class: 'card-link mr-3'
                                    - if goal.user_id == current_user&.id
                                        = link_to_if goal.user_id == current_user.id, '積み上げ記録を追加', new_goal_action_record_path(goal),
                                            class: 'card-link mr-3'
                    = paginate @goals, param_name: 'goal_page'
                .col-md-1
    #action_record.tab-pane.fade aria-labelledby="action_record-tab" role="tabpanel"
        br
        .container
        = render partial: 'goal'
        .container
            .row
                .col-md-1
                .col-md-10.col-sm-12
                    - if current_user.present? && current_user.action_records.blank?
                        .card.bg-light.mb-3
                            .card-body 
                                .card-title 
                                    h5 積み上げ記録をつけてみよう!
                                .card-text
                                    = link_to '積み上げる', user_goals_path(id: current_user.id), class:'btn btn-primary mt-3'
                    - @action_records.each do |action_record|
                        .card.bg-light.my-3
                            .card-body
                                .row
                                    .col-4.col-md-2
                                        .card-text
                                            - if action_record.action_image_url.present?
                                                = image_tag action_record.action_image_url, class:'', width: '80px'
                                            - else
                                                = image_tag 'record.PNG', class:'', width: '80px'
                                            br
                                    .col-8.col-md-8
                                        h5.card-title
                                            br
                                            = action_record.goal_action.action_name
                                .row
                                    .col-12
                                        .scroll
                                            p.card-text
                                                = simple_format(action_record.action_comment)
                                        p.card-text
                                            = link_to "#{action_record.action_url}","#{action_record.action_url}", target: :_blank
                                        small.card-text
                                            = action_record.updated_at.strftime("%Y年%m月%d日 %H時%M分")
                                            = link_to "By #{action_record.user.display_name}", user_path(action_record.user.id), class: 'ml-2'
                                p.card-text
                                    i.fa.fa-star
                                    = "達成Lv.#{action_record.goal.rank}"
                                    .progress 
                                        .progress-bar.progress-bar-striped aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" style="width: #{action_record.goal.rank * 10}%"
                                h6.card-text
                                    = link_to "#{action_record.goal.goal_category.name}", goals_path(goal_category_id:action_record.goal.goal_category.id),
                                        class: 'btn btn-outline-primary btn-sm mr-1'
                                    = link_to '目標詳細', goal_path(action_record.goal), class: 'card-link mr-3'
                                p.card-text.text-right
                                    - if action_record.user_id == current_user&.id
                                        = link_to_if action_record.user_id == current_user.id, '編集', edit_action_record_path(action_record), class: 'btn btn-primary mr-3 text-right'
                                        = link_to_if action_record.user_id == current_user.id,'削除', action_record_path(action_record), method: :delete, remote: true,class: 'btn btn-primary mr-3'
                    = paginate @action_records, param_name: 'action_record_page'
                .col-md-1

app/views/goals/show.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h4 #{@goal.goal_content}の目標詳細
            p.text-right
                = link_to "by#{@goal.user.display_name}", user_path(@goal.user)
            table.table.table-striped.table-bordered
                thead
                    tbody
                            tr
                                td.font-weight-bold 目標
                            tr
                                td = @goal.goal_content
                            - @goal_actions.each.with_index(1) do |goal_action, index|
                                tr
                                    td.font-weight-bold 行動#{index}
                                tr
                                    td = goal_action.action_name
                            tr
                                td.font-weight-bold 価値観
                            tr
                                td = @goal.identity_content
                            tr
                                td.font-weight-bold カテゴリ
                            tr
                                td = @goal.goal_category.name
            - if @goal.user_id == current_user&.id
                .text-right
                    = link_to_if @goal.user_id == current_user.id, '編集', edit_goal_path(@goal), class: 'btn btn-primary mr-3 text-right'
                    = link_to_if @goal.user_id == current_user.id,'削除', goal_path(@goal), method: :delete, remote: true,class: 'btn btn-primary mr-3'
            br
            = link_to '行動一覧', goal_goal_actions_path(@goal), class: 'btn btn-light mr-3'
            = link_to '積み上げ記録一覧', goal_action_records_path(@goal), class: 'btn btn-light mr-3'
        .col-md-1

app/views/goals/user.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h4 積み上げ記録を追加
        .col-md-1
= render partial: 'goal'
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            - if current_user.present? && current_user.action_records.blank?
                .card.bg-light.mb-3
                    .card-body 
                        .card-title 
                            h5 積み上げ記録をつけてみよう!
            - @goals.each do |goal|
                .card.bg-light.my-3
                    .card-body
                        h5.card-title
                            .text-center
                                = goal.goal_content
                                br
                                = image_tag "tree_#{goal.rank}.PNG", class: 'image m-4', width: '200px'
                        p.card-text
                            i.fa.fa-star = "達成Lv.#{goal.rank}"
                            .progress
                                    .progress-bar.progress-bar-striped aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" style="width: #{goal.rank * 10}%"
                        - if goal.user_id == current_user&.id
                            = link_to_if goal.user_id == current_user.id, '積み上げる', new_goal_action_record_path(goal),
                                class: 'btn btn-primary btn-block'
                        h6.card-text
                            = link_to '詳細', goal_path(goal), class: 'btn btn-light btn-block mt-2'
        .col-md-1